### ISSUE TITLE
Error: GraphQL Error (Code: 401)

### ISSUE THREAD

**Issue by RolandsKundzins** [Shopify/shopify-app-template-remix#330]
# Issue summary

Whenever I start my shopify app, within about one hour I get a grapql 401 error. At first it was on my main project, but than I created a new one and still the same issue even on another computer and partner account.
My suspicion is that it might be something to deal with checkout extensions, but it could be anything.

I didn't yet up the log level, but I will add the log message once I get the error again.

- `@shopify/shopify-app-remix` version: 1.0.3
- Node version: v18.17.1 (also tried v20.5.1)
- Operating system: windows 10

```
Error: GraphQL Error (Code: 401): {"response":{"error":"","status":401,"headers":{}},"request":{"query":"\n  query FindApp($apiKey: String!) {\n    app(apiKey: $apiKey) {\n      developmentStorePreviewEnabled\n    }\n  }\n","variables":{"apiKey":"<my_api_key_here>"}}}
at makeRequest (file:///.../node_modules/graphql-request/build/esm/index.js:284:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async debugLogResponseInfo (file:///.../node_modules/@shopify/cli-kit/dist/private/node/api.js:13:20)
at async graphqlRequest (file:///.../node_modules/@shopify/cli-kit/dist/public/node/api/graphql.js:20:22)
```

## Expected behavior

No error should be thrown and the app should keep working.

## Actual behavior

After about one hour an error is thrown. Another guy too got the error and said that it only took him 10 minutes: 
[graphql-401-error-after-one-hour-of-idle](https://community.shopify.com/c/shopify-apps/graphql-401-error-after-one-hour-of-idle/m-p/2211965#M67774)

## Steps to reproduce the problem

1. npm init @Shopify/app@latest //chose remix
2. cd your-app
3. npm run shopify app generate extension //checkout ui
4. npm run dev
5. Went into the app and checked that I have the checkout extension
6. Wait about 1-2 hours and the previously mentioned error appears.

**Comment by byrichardpowell** [comment]
Hey there,

Sorry about this. I'm going to follow up with the team internally to see what's going on here.

**Comment by RolandsKundzins** [comment]
Thanks for the quick response. BTW, I did try to increase log level, but still got the same error message.

**Comment by andrewclo** [comment]
Same issue here.

**Comment by hugop-lg** [comment]
After updated cli to last version [v3.51.1] the problem persists

**Comment by lizkenyon** [comment]
Closing this issue. 

If you are still experiencing this, please create a new issue. Thanks!

**Comment by abdullahceylan** [comment]
For anyone still experiencing the issue:

Delete the `.shopify` folder from the root of your app, then restart the app using the Shopify CLI. You’ll be prompted to log in to Shopify for verification, and everything should work fine afterward.
