### ISSUE TITLE
Issues with latest releases when creating an app

### ISSUE THREAD

**Issue by nicetransition** [Shopify/shopify-app-template-remix#404]
# Issue summary

I am running into several issues with the latest version of ` @shopify/shopify-app-remix` and `shopify-app-template-remix`. After setting up the project with my Partner account and providing a name, running `npm run dev` puts me a through a constant path of having to reconnect to my Partner organization, when I do I get `Update URLs:  Not yet configured` - which I have never seen this issue before. But then it consoles the following:

```
15:15:23 │ remix │ 
15:15:23 │ remix │  💿  remix dev
15:15:23 │ remix │ 
15:15:23 │ remix │  info  building...
15:15:24 │ remix │  info  built (481ms)
15:15:24 │ remix │ Error: Cannot find module 
'~/my-app-name-here/node_modules/@shopify/shopify-api/rest/admin/2023-10/index.js'
15:15:24 │ remix │     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
15:15:24 │ remix │     at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
15:15:24 │ remix │     at resolveExports (node:internal/modules/cjs/loader:565:14)
15:15:24 │ remix │     at Function.Module._findPath (node:internal/modules/cjs/loader:634:31)
15:15:24 │ remix │     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
15:15:24 │ remix │     at Function.Module._load (node:internal/modules/cjs/loader:920:27)
15:15:24 │ remix │     at Module.require (node:internal/modules/cjs/loader:1141:19)
15:15:24 │ remix │     at require (node:internal/modules/cjs/helpers:110:18)
15:15:24 │ remix │     at Object.<anonymous> (~/my-app-name-here/app/shopify.server.js:9:31)
15:15:24 │ remix │     at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

In addition, when running `npm start` I get the following:

```
> start
> remix-serve build/index.js

Error: Cannot find module '~/my-app-name-here/node_modules/@shopify/shopify-api/rest/admin/2023-10/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
    at resolveExports (node:internal/modules/cjs/loader:565:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (~/my-app-name-here/app/shopify.server.js:9:31)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

Running `npm run build` builds but it just a blank file when opened/run.

- `@shopify/shopify-app-remix` version: `^2.0.2`
- Node version: `v18.14.2`
- Operating system: `macOs Sonoma 14.1`

**Comment by Jarvie789** [comment]
Yes, try ngrok. 
I use ngrok and it works fine, but shopify-cli cannot start the remix server.

**Comment by nicetransition** [comment]
Yeah, it's a bit of a pain. I wish this had it working from the start. I was trying to get some config files and package.json updates to make it be consistent, but just have to run it a bit custom/down and dirty.

**Comment by xstortionist** [comment]
> Yeah, it's a bit of a pain. I wish this had it working from the start. I was trying to get some config files and package.json updates to make it be consistent, but just have to run it a bit custom/down and dirty.

Of course, once I got it working I was presented with another error. Might be time to hang up these WSL gloves and migrate over to ubuntu.
