### ISSUE TITLE
Node-gyp error when installing dependencies 

### ISSUE THREAD

**Issue by leindfraust** [Shopify/shopify-app-template-remix#543]
# Issue summary

I get a node-gyp error when installing dependencies. It seems a command has failed `C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild` . I already have node-gyp installed globally too. I already tried to `ncu` or bump all packages version to date and still no luck. Already also tried with `npm install --force` and `npm install --legacy-peer-deps` on the repo itself. 

- `@shopify/shopify-app-remix` version: 2.4.0
- Node version: 20.11.0
- Operating system: Windows 11

```
Error coming from `npm install`

Command failed with exit code 1: npm install
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript
standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript
standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup
'C:\\Users\\ronan\\AppData\\Local\\Temp\\b9f7951e597b6ac1a813eccc84b4a7d5\\app\\node_modules\\@shopify\\app',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\ronan\AppData\Local\Temp\b9f7951e597b6ac1a8
13eccc84b4a7d5\app\node_modules\@shopify\app\node_modules\@shopify\polaris\build\ts\src\components\Tabs'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ronan\\AppData\\Local\\Temp\\b9f7951e597b6ac1a813eccc84b4a7d5\\app\\node_module
s\\@shopify\\app\\node_modules\\@shopify\\polaris\\build\\ts\\src\\components\\Tabs'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\ronan\\AppData\\Local\\Temp\\b9f7951e597b6ac1a813eccc84b4a7d5\\app\\node_modules\\@shop
ify\\app\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\ronan\AppData\Local\Temp\b9f7951e597b6ac1a8
13eccc84b4a7d5\app\node_modules\@shopify\app\node_modules\@shopify\polaris\build\ts\src\components\Navigation'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ronan\\AppData\\Local\\Temp\\b9f7951e597b6ac1a813eccc84b4a7d5\\app\\node_module
s\\@shopify\\app\\node_modules\\@shopify\\polaris\\build\\ts\\src\\components\\Navigation'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\ronan\AppData\Local\Temp\b9f7951e597b6ac1a813eccc84b4a7d5\app\node_modules\@parcel\watcher
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.11.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.34301.259) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\ronan\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\ronan\\AppData\\Local\\Temp\\b9f7951e597b6ac1a813eccc84b4a7d5\\app\\node_modu
les\\@parcel\\watcher\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\ronan\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\ronan\\AppData\\Local\\node-gyp\\Cache\\20.11.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ronan\\AppData\\Local\\node-gyp\\Cache\\20.11.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\ronan\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\ronan\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.11.0
\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\ronan\\AppData\\Local\\Temp\\b9f7951e597b6ac1a813eccc84b4a7
d5\\app\\node_modules\\@parcel\\watcher',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args
'C:\\Users\\ronan\\AppData\\Local\\Temp\\b9f7951e597b6ac1a813eccc84b4a7d5\\app\\node_modules\\@parcel\\watcher\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\ronan\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "C:\Users\ronan\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "C:\Users\ronan\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\ronan\node_modules\node-gyp\lib\configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22631
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe"
"C:\\Users\\ronan\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd
C:\Users\ronan\AppData\Local\Temp\b9f7951e597b6ac1a813eccc84b4a7d5\app\node_modules\@parcel\watcher
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
C:\Users\ronan\AppData\Local\npm-cache\_logs\2024-02-08T01_37_09_309Z-debug-0.log

────────────────────────────────────────────────────────────────────────────────

npm ERR! code 1
npm ERR! path C:\Users\ronan\Documents\Projects\Shopify\Task
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-app

npm ERR! A complete log of this run can be found in: C:\Users\ronan\AppData\Local\npm-cache\_logs\2024-02-08T01_36_52_899Z-debug-0.log
```

## Expected behavior

Should install the packages

## Actual behavior

Throws a node-gyp error but already installed node-gyp globally.

## Steps to reproduce the problem

1. Clone this repository or through CLI `npm init @shopify/app@latest`
2. In repo, npm install or in CLI wait for it to install dependencies until it returns the error

**Comment by leindfraust** [comment]
Upon researching, it seems the error stems from having Python 3.10 and up as distutils is deprecated as explained [here](https://peps.python.org/pep-0632/)

`pip install setuptools` seems to resolve this issue `npm ERR! ModuleNotFoundError: No module named 'distutils'`

I also had a problem with the `@parcel/watcher` throwing an error `npm ERR! gyp: binding.gyp not found`. I found a workaround by overriding it on `package.json` 

```javascript
"overrides": {
    "@parcel/watcher": "2.1.0"
},
```

Now everything works correctly.

**Comment by leindfraust** [comment]
Will reopen this issue for now to anyone encountering the same problem

**Comment by Eusebiotrigo** [comment]
And we cannot use the npm init @shopify/app@latest command, right?

**Comment by leindfraust** [comment]
> Have you got it to work?

Yes, clone this repo and to your package.json, put this

```javascript
"overrides": {
    "@parcel/watcher": "2.1.0"
},
```

**Comment by darrynten** [comment]
Is there a way to make the `init` work without cloning this repo?

**Comment by shauns** [comment]
@darrynten you have a fair few options for workarounds if this is affecting you, at least until any issue is resolved -- the `init` command doesn't do too much beyond cloning & installing dependencies:

- [recommended] you can clone this repo, tweak dependencies as needed, and then run `dev` etc.
- you can choose "extension-only" app, and then add a web app to that
- you can fork this template and use the `--template` option to choose a different repo/branch
- you can create a project from scratch -- you'll need a `shopify.app.toml` and a `shopify.web.toml` for the web part
