### ISSUE TITLE
Following the the new 2024-04 update and based on the latest commits, how do I specify an specific admin api version in the `.graphqlrc.ts` file without it throwing an error?

### ISSUE THREAD

**Issue by muchisx** [Shopify/shopify-app-template-remix#674]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version: "@shopify/api-codegen-preset": "0.0.7",
  - Node version: 20.11
  - Operating system: Windows 11
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API

## Expected behavior

What do you think should happen?
I should be able to set a specific api version for the graphqlrc aswell without errors

## Actual behavior
We get an error when running `npm run graphql-codegen` if using a specific api version

## Steps to reproduce the problem

1. Use the code that was reverted in this commit https://github.com/Shopify/shopify-app-template-remix/commit/a4c59fbc71291034e9ffce4d73df058602cb4633
2. run  `npm run graphql-codegen`
3. See ithe terminal break with `ShopifyError: Invalid appUrl provided. Please provide a valid URL.`

## Debug logs

```shell
ShopifyError: Invalid appUrl provided. Please provide a valid URL.
    at deriveApi (D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\node_modules\@shopify\shopify-app-remix\build\cjs\server\shopify-app.js:98:11)
    at shopifyApp (D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\node_modules\@shopify\shopify-app-remix\build\cjs\server\shopify-app.js:49:15)
    at D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\app\shopify.server.ts:9:40
    at evalModule (D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\node_modules\jiti\dist\jiti.js:1:256443)
    at jiti (D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\node_modules\jiti\dist\jiti.js:1:254371)
    at D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\.graphqlrc.ts:3:16
    at evalModule (D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\node_modules\jiti\dist\jiti.js:1:256443)
    at jiti (D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\node_modules\jiti\dist\jiti.js:1:254371)
    at loadTypeScript (D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\node_modules\graphql-config\cjs\helpers\cosmiconfig.js:39:12)
    at #loadConfiguration (D:\Projects\Miguel Ángel - Work\Miguel Ángel x Programming\SouthFlorals - Shopify\nuflorist-official\node_modules\cosmiconfig\dist\Explorer.js:92:30) {
  filepath: 'D:\\Projects\\Miguel Ángel - Work\\Miguel Ángel x Programming\\SouthFlorals - Shopify\\nuflorist-official\\.graphqlrc.ts'
```

**Comment by muchisx** [comment]
Hi! I will try thanks!

but isn't that what is being exported from the shopify.server.ts file already? 

`export const apiVersion = ApiVersion.April24;`

**Comment by lizkenyon** [comment]
Yes, unfortunately that does not work right, now which is why that commit was reverted. So you will have to define the API version in both places at this time. We hope to get this working in the future.

**Comment by muchisx** [comment]
@lizkenyon Thank you for your time!
Got it, so I just did 
`import { ApiVersion } from '@shopify/shopify-api';`

and used the `ApiVersion.TheOneINeed` in the `.graphqlrc.ts` file as you suggested, it works!
