### ISSUE TITLE
Shopify app hydration error

### ISSUE THREAD

**Issue by thanigai-babu17** [Shopify/shopify-app-template-remix#731]
Node: v20.14.0
Shopify CLI: 3.61.0

I've been seeing the error below in my terminal from the start, but I didn't have any hydration errors initially. Then, suddenly, hydration errors started to appear, especially when I installed the Firebase client. I tried uninstalling Firebase and then ran shopify app dev --reset, but the issue persisted. I deleted my node_modules and cleared the cache, but I still saw the error. Randomly, it didn't occur, but then it started appearing again. I tried debugging for almost a day but still couldn't resolve it. I'm not sure why this is happening, but it is really frustrating.

<pre>4:48:39 pm [vite] error while updating dependencies:
16:48:39 │ <font color="#A347BA">remix        </font> │ Error: Build failed with 2 errors:
16:48:39 │ <font color="#A347BA">remix        </font> │ node_modules/farmhash/index.js:5:19: ERROR: No loader is configured for &quot;.node&quot; files: node_modules/farmhash/build/Release/farmhash.node
16:48:39 │ <font color="#A347BA">remix        </font> │ node_modules/farmhash/index.js:7:19: ERROR: Could not resolve &quot;./build/Debug/farmhash.node&quot;
16:48:39 │ <font color="#A347BA">remix        </font> │     at failureErrorWithLog (/home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
16:48:39 │ <font color="#A347BA">remix        </font> │     at /home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
16:48:39 │ <font color="#A347BA">remix        </font> │     at /home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
16:48:39 │ <font color="#A347BA">remix        </font> │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
16:48:43 │ <font color="#A347BA">remix        </font> │ [shopify-app/INFO] Authenticating admin request
16:48:43 │ <font color="#A347BA">remix        </font> │ ✘ [ERROR] Could not resolve &quot;./build/Debug/farmhash.node&quot;
16:48:43 │ <font color="#A347BA">remix        </font> │
16:48:43 │ <font color="#A347BA">remix        </font> │     node_modules/farmhash/index.js:7:19:
16:48:43 │ <font color="#A347BA">remix        </font> │       7 │     return require(&apos;./build/Debug/farmhash.node&apos;);
16:48:43 │ <font color="#A347BA">remix        </font> │         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:48:43 │ <font color="#A347BA">remix        </font> │
16:48:43 │ <font color="#A347BA">remix        </font> │ ✘ [ERROR] No loader is configured for &quot;.node&quot; files: node_modules/farmhash/build/Release/farmhash.node
16:48:43 │ <font color="#A347BA">remix        </font> │
16:48:43 │ <font color="#A347BA">remix        </font> │     node_modules/farmhash/index.js:5:19:
16:48:43 │ <font color="#A347BA">remix        </font> │       5 │     return require(&apos;./build/Release/farmhash.node&apos;);
16:48:43 │ <font color="#A347BA">remix        </font> │         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:48:43 │ <font color="#A347BA">remix        </font> │
16:48:44 │ <font color="#A347BA">remix        </font> │ 4:48:44 pm [vite] error while updating dependencies:
16:48:44 │ <font color="#A347BA">remix        </font> │ Error: Build failed with 2 errors:
16:48:44 │ <font color="#A347BA">remix        </font> │ node_modules/farmhash/index.js:5:19: ERROR: No loader is configured for &quot;.node&quot; files: node_modules/farmhash/build/Release/farmhash.node
16:48:44 │ <font color="#A347BA">remix        </font> │ node_modules/farmhash/index.js:7:19: ERROR: Could not resolve &quot;./build/Debug/farmhash.node&quot;
16:48:44 │ <font color="#A347BA">remix        </font> │     at failureErrorWithLog (/home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
16:48:44 │ <font color="#A347BA">remix        </font> │     at /home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
16:48:44 │ <font color="#A347BA">remix        </font> │     at /home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
16:48:44 │ <font color="#A347BA">remix        </font> │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
16:48:47 │ <font color="#A347BA">remix        </font> │ [shopify-app/INFO] Authenticating admin request
16:48:47 │ <font color="#A347BA">remix        </font> │ [shopify-app/INFO] Authenticating admin request
16:48:48 │ <font color="#A347BA">remix        </font> │ ✘ [ERROR] Could not resolve &quot;./build/Debug/farmhash.node&quot;
16:48:48 │ <font color="#A347BA">remix        </font> │
16:48:48 │ <font color="#A347BA">remix        </font> │     node_modules/farmhash/index.js:7:19:
16:48:48 │ <font color="#A347BA">remix        </font> │       7 │     return require(&apos;./build/Debug/farmhash.node&apos;);
16:48:48 │ <font color="#A347BA">remix        </font> │         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:48:48 │ <font color="#A347BA">remix        </font> │
16:48:48 │ <font color="#A347BA">remix        </font> │ ✘ [ERROR] No loader is configured for &quot;.node&quot; files: node_modules/farmhash/build/Release/farmhash.node
16:48:48 │ <font color="#A347BA">remix        </font> │
16:48:48 │ <font color="#A347BA">remix        </font> │     node_modules/farmhash/index.js:5:19:
16:48:48 │ <font color="#A347BA">remix        </font> │       5 │     return require(&apos;./build/Release/farmhash.node&apos;);
16:48:48 │ <font color="#A347BA">remix        </font> │         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:48:48 │ <font color="#A347BA">remix        </font> │
16:48:48 │ <font color="#A347BA">remix        </font> │ 4:48:48 pm [vite] error while updating dependencies:
16:48:48 │ <font color="#A347BA">remix        </font> │ Error: Build failed with 2 errors:
16:48:48 │ <font color="#A347BA">remix        </font> │ node_modules/farmhash/index.js:5:19: ERROR: No loader is configured for &quot;.node&quot; files: node_modules/farmhash/build/Release/farmhash.node
16:48:48 │ <font color="#A347BA">remix        </font> │ node_modules/farmhash/index.js:7:19: ERROR: Could not resolve &quot;./build/Debug/farmhash.node&quot;
16:48:48 │ <font color="#A347BA">remix        </font> │     at failureErrorWithLog (/home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
16:48:48 │ <font color="#A347BA">remix        </font> │     at /home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
16:48:48 │ <font color="#A347BA">remix        </font> │     at /home/thanigai/works/a360-discounts/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
16:48:48 │ <font color="#A347BA">remix        </font> │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</pre>

![image](https://github.com/Shopify/shopify_app/assets/93237442/6d97859e-8dcd-49dd-bc7d-f16bc3f4343a)

`  "dependencies": {
    "@prisma/client": "^5.11.0",
    "@remix-run/dev": "^2.7.1",
    "@remix-run/node": "^2.7.1",
    "@remix-run/react": "^2.7.1",
    "@remix-run/serve": "^2.7.1",
    "@shopify/app-bridge-react": "^4.1.2",
    "@shopify/polaris": "^12.0.0",
    "@shopify/shopify-api": "^11.0.0",
    "@shopify/shopify-app-remix": "^3.0.0",
    "@shopify/shopify-app-session-storage-prisma": "^5.0.0",
    "firebase-admin": "^12.1.1",
    "formik": "^2.4.6",
    "isbot": "^5.1.0",
    "prisma": "^5.11.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "vite-tsconfig-paths": "^4.3.1"
  },`

**Comment by thanigai-babu17** [comment]
hydration error specifically happens when i add new dependencies
