### ISSUE TITLE
Docker ignoring build dir. package.json start needs "remix-serve ./build/server/index.js"

### ISSUE THREAD

**Issue by tajbowness** [Shopify/shopify-app-template-remix#779]
Hello, I'm trying to deploy, but I get this error

```
> NODE_OPTIONS='--import ./instrumentation.server.mjs' remix-serve ./build/server/index.js

Error: ENOENT: no such file or directory, stat '/app/build/server/index.js'
    at Object.statSync (node:fs:1676:25)
    at reimportServer (/app/node_modules/@remix-run/serve/dist/cli.js:83:39)
    at run (/app/node_modules/@remix-run/serve/dist/cli.js:112:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I think this is because in the `.dockerignore` file it includes `build` to be ignored.

But in `package.json`, its needed to start `remix-serve ./build/server/index.js.`  Apologies, am I missing something?

**Comment by paulomarg** [comment]
Hi, thanks for raising this. Are you using the template's default `Dockerfile`?

Currently, it is set up to run `npm run build` (see [code](https://github.com/Shopify/shopify-app-template-remix/blob/main/Dockerfile#L14)), because you'll need to build the app before it can be run.

In any case, running the build command should fix the issue. Hope this helps!

**Comment by tajbowness** [comment]
Hey @paulomarg,

That's correct, default `Dockerfile`.

The issue seemed to be with `build` being set to `"build": "vite build && vite build"` , I believe this was the value when I first installed the template.

I've updated it to `"build": "remix vite:build"` . Works properly now! Thanks for the insight :)
