### ISSUE TITLE
Shopify GraphQL API Library Error

### ISSUE THREAD

**Issue by JadielSantos** [Shopify/shopify-app-template-remix#866]
Hi there.

I implemented a route with an action that receives an SKU and the number of available inventory items.
I also have a service sending many requests to this route, so my store's inventory is constantly updated.
I'm facing the following error when trying to send Graphql queries and mutations to our store with an unauthenticated context `const { admin, session } = await unauthenticated.admin(shopUrl);`:
"HttpRequestError: Http request error, no response available: GraphQL Client: request to https://xyz.myshopify.com/admin/api/2024-07/graphql.json failed, reason:"
It's not a "bad request" or something related to the query or variables of the requests, it works for some time and then intermittently returns this error.
The support said it's not reaching the Shopify API because I don't receive the x-request-id for those error requests.

This is the stack trace I have in return from admin.graphql():
Error: Http request error, no response available: GraphQL Client: request to https://xyz.myshopify.com/admin/api/2024-07/graphql.json failed, reason:
    at action$d (file:///app/build/server/index.js?t=1727968757000:5427:95)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.callRouteAction (/app/node_modules/@remix-run/server-runtime/dist/data.js:37:16)
    at /app/node_modules/@remix-run/router/router.ts:4817:21
    at callLoaderOrAction (/app/node_modules/@remix-run/router/router.ts:4879:16)
    at async Promise.all (index 1)
    at callDataStrategyImpl (/app/node_modules/@remix-run/router/router.ts:4720:17)
    at callDataStrategy (/app/node_modules/@remix-run/router/router.ts:3975:19)
    at submit (/app/node_modules/@remix-run/router/router.ts:3737:21)
    at queryImpl (/app/node_modules/@remix-run/router/router.ts:3666:22)

Can someone help find out this error?

**Comment by KthProg** [comment]
I fixed this for us by increasing the default timeout for network connections in node:
`import net from 'net';
net.setDefaultAutoSelectFamilyAttemptTimeout(5000);`
