### ISSUE TITLE
shopify.app.toml adds trailing / to App URL, causing graphql errors on Proxy URL hit

### ISSUE THREAD

**Issue by loreleim** [Shopify/shopify-app-template-remix#879]
As of early this week, the same configs I have on my Render built app haven't been working. I am seeing this error within my Render dashboard when a proxy endpoint is hit by the FE. 

[shopify-app/INFO] Authenticating app proxy request
TypeError: Cannot read properties of undefined (reading 'graphql')
    at action$1 (file:///app/build/server/index.js?t=1730406106000:901:36)
    at Object.callRouteAction (/app/node_modules/@remix-run/server-runtime/dist/data.js:36:16)
    at /app/node_modules/@remix-run/router/router.ts:4899:19
    at callLoaderOrAction (/app/node_modules/@remix-run/router/router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (/app/node_modules/@remix-run/router/router.ts:4772:17)
    at callDataStrategyImpl (/app/node_modules/@remix-run/router/router.ts:4835:17)
    at callDataStrategy (/app/node_modules/@remix-run/router/router.ts:3992:19)
    at submit (/app/node_modules/@remix-run/router/router.ts:3755:21)
    at queryImpl (/app/node_modules/@remix-run/router/router.ts:3684:22)

Testing Steps: 

Checking the APP config on deploy

1. Shopify Partners > Apps > Build > Configuration > URLS
2. remove trailing / generated by build
3. Check toml file doesn't include a / by default  

App doesn't seem to be having a permissions issue as I can see it working within the first minute of saving the config. Including, testing on the `npm run dev` local build where a trailing / is not added to the cloudflare urls. anyone seeing issues with non-local builds?

**Comment by lizkenyon** [comment]
Hi there 👋 

Could you confirm that when you remove the trailing slash in the partner dashboard the error you are seeing goes away?

**Comment by ccarlosm** [comment]
I had a similar issue recently, and in my case, it wasn’t due to permissions either. The problem turned out to be a malformed JSON key in the locale files—specifically, a key like "text2.1": "text for the translation", which isn’t a valid JSON key format. However, there were no warnings or errors in the console, so it took a while to identify. 

While this might not be the exact cause of your issue, I’d recommend reviewing any recent code changes, even if they don’t seem directly related. There could be a small configuration error that’s affecting the proxy unexpectedly.
